repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.3
    hooks:
      -   id: flake8
  # - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  #   rev: v1.2.0
  #   hooks:
  #     - id: check-model-has-description
  #       args: ["--manifest", "./ghdata/target/manifest.json", "--"]
  #     - id: check-model-has-all-columns
  #       args: ["--catalog", "./ghdata/target/catalog.json", "--manifest", "./ghdata/target/manifest.json","--"]
  #     - id: check-model-has-tests
  #       args: ["--manifest", "./ghdata/target/manifest.json", "--test-cnt", "2", "--"]
